#!/bin/sh

# Заставляем браузер использовать libhardened_malloc
# Оно работает!
# :3
# Изолируем браузер,bwrap запускаем с библеотекой hardened_malloc и браузер внутри песочницы тоже
LB_PRELOAD="/usr/lib/libhardened_malloc.so" bwrap --bind / / --dev /dev --proc /proc --tmpfs /tmp --setenv LB_PRELOAD "/usr/lib/libhardened_malloc.so" --ro-bind /usr /usr --ro-bind /lib /lib --ro-bind /etc /etc --unshare-all --share-net --unshare-pid --unshare-uts --unshare-ipc --unshare-user /usr/bin/librewolf "$@"
