#!/bin/sh

LB_PRELOAD="/usr/lib/libhardened_malloc.so" bwrap --bind / / --setenv LB_PRELOAD "/usr/lib/libhardened_malloc.so" --unshare-all --ro-bind /usr /usr --ro-bind /lib /lib --ro-bind /etc /etc --share-net --unshare-pid --unshare-uts --unshare-ipc --unshare-user /usr/bin/wget --header="User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" --header="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" --header="Accept-Language: en-US,en;q=0.5" "$@"
