#!/bin/sh

################################
# Скрытие реального machine-id #
################################

#Подмена на machine-id от Whonix
echo "b08dfa6083e7567a1921a715000001fb" > /var/lib/dbus/machine-id
