#!/bin/bash

#################
# Настройки DNS #
#################

# Список DNS-серверов
# Quad9,DNS.watch,OpenDNS....
dns_servers=(
    "149.112.112.112"    
    "84.200.69.80"   
    "84.200.70.40"
    "9.9.9.9"
    "208.67.222.222"
    "208.67.220.220"
)

random_dns=${dns_servers[$RANDOM % ${#dns_servers[@]}]}

printf "nameserver 127.0.0.1\nnameserver ${random_dns}" > /etc/resolv.conf 
